### ISSUE TITLE
Allow custom sorting order

### ISSUE THREAD

**Issue by tsela** [Alamantus/Lexiconga#14]
This looks like a great dictionary builder, and something I've been looking for for a long time :). I'll be trying it out, but right now I wanted to point out a possible enhancement I'd like to see happen: make it possible to have a _custom sort order_.
Even if you limit yourself to the Latin alphabet, not all languages sort words the same way, and conlangs are also likely to have a different native sort order. Some language may sort specific digraphs separately from the letters they are composed of (like how in Spanish _ch_ and _ll_ used to be separate letters), others may sort letters with diacritics as separate from the equivalent without diacritics. Some can do both (have a look at the Albanian alphabet!). So it'd be great to be able to define a custom sort order for the dictionary in its settings area. You could, for instance, make it a comma-separated list like the _Part of Speech_ dialog, with letters or group of letters that form a single sort category separated by spaces. For instance, something like:

A a,Á á,B b,C c,D d,E e,É é,F f,G g,H h,I i,Í í,J j,K k,L l,M m,N n,O o,Ó ó,P p,Q q,R r,S s,T t,U u,Ú ú,V v,W w,X x,Y y,Z z

would specify a case-insensitive word order where acute-accented vowels are treated as separate letters (I'm basically borrowing the format from SIL Toolbox. You may want to do something different, especially in terms of case-sensitivity). This is just an example, but I hope you get the idea.

I think it'd be a very useful feature.  I hope you agree :).

**Comment by Alamantus** [comment]
Finished on commit 572b49a660e9548bfd43cf3f62f778e3dcd46ecd  
Will close when launched.
