### ISSUE TITLE
Definition/Equivalent Word(s) field gets truncated

### ISSUE THREAD

**Issue by tsela** [Alamantus/Lexiconga#17]
OK, once again in the series "fields are too short", the "Definition/Equivalent Word(s)" field of each entry is just slightly too short for me (I think doubling its length would be enough). Because my conlang is really not a relex, giving equivalent words in English of one word in Haotyétpi sometimes requires me to give a long list in that field. And I don't want to just use the "long definition" field because I like to use the shorter field as a list of glosses, separate from the longer description itself (and I like how it looks on the page).

An alternative would be to allow single entries to have multiple _senses_, each with their own "Definition/Equivalent Word(s)" and "Explanation/Long Definition" fields. That would allow me to separate the glosses into smaller, sense-relevant groups (just allowing duplicate entries is not good enough, as those are for homonyms/homophones, not for words that are single words but with various meanings, when translating in English). I could imagine, however, that this would require quite a lot of work to implement properly.

**Comment by Alamantus** [comment]
I have extended the Definition/Equivalent Word(s) field from 100 characters to 250 characters! Sorry it took me so long to make this change.

I'll be working on improving the duplicate entries feature by allowing you to manually number the words as you suggested in another issue, so this fix may not be completely necessary in the future.

**Comment by tsela** [comment]
Great! Indeed, a better handling of homonyms and words with separate senses will likely make this unneeded, but I actually like string fields that are unlikely to max out anyway :).

Thanks for the change! I have been busy with other things so haven't worked much with Lexiconga lately, but once I get back on track I will resume putting my Haotyétpi dictionary there :).

Cheers!
