### ISSUE TITLE
Smart Cross-links and Numbered Homonyms

### ISSUE THREAD

**Issue by tsela** [Alamantus/Lexiconga#18]
Hi!

Me again :). I haven't noticed any new bugs so far, so instead I'd like to propose some possible enhancements. I'm using a single issue post to mention them all, but feel free to separate them into separate issues if you prefer it that way. These are mostly things I think would be nice to have. In any case, these are features I think would make the life of the user easier.

In no particular order:

It's nice that Lexiconga allows duplicate entries, as homonyms are a natural feature of languages. What would be even better is that when homonyms are present, each one would be marked by a subscript number, as is usually done in dictionaries. I know such a feature may seem useless right now, but you'll understand why I think it would be useful once I talk about the next possible feature.

It's an absolutely fantastic feature that entries in a Lexiconga dictionary can be cross-linked, and I am using these links within page liberally. It's the one feature I'm missing from the other dictionary creation software I'd been using so far and I love it! However, right now it's a bit of a pain to use, as you need to:
- scroll to the entry you want to link to;
- copy that link location using the right-click menu or just remember it;
- go to the entry you want to link that entry to;
- paste the link within the Markdown text where it belongs, or type the link yourself;
- rinse and repeat...

I've done it quite a lot already, and believe me it gets very old very quickly, especially since the main use case for this is to simply turn a word in the language in some other entry into a link to that word's entry, i.e. this means I get to type a lot of `[some dictionary word](link to that word's entry in the dictionary)`. What would be great would be to automate much of this process, and I think this should be possible.

My idea would be like this: before running the entry text through the Markdown parser, pass it through another parser that would recognise dictionary entries in the text. Because that might be a bit too complex, you could simply mark them in some way (my favourite would be surrounding such an entry with `<>`, since it's tradition in linguistics to quote words in a target language that way, but since Markdown recognises that as something already this might lead to issues. An alternative could be something like `<:entry>`, with the colon ensuring this cannot be confused with a Markdown explicit URL, although you may invent your own tagging if you think this would simplify parsing). When the software would encounter something like `<:entry>` (or whatever you want it to be), it would look up "entry" in the dictionary. If it finds it, it would grab the link to that entry, and replace `<:entry>` with `[entry](http://lexicon.ga/#link_to_entry)`. Then the text could be sent through the Markdown parser and the result would be a correct link, without the user having to hunt for the link themselves.

That's also why numbered homonyms would then be necessary: to distinguish them in the above case (the syntax could be something like `<:entry2>` for the second homonym for that entry, or `<:entry.2>` if that's easier to parse).

Anyway, I hope you get the idea. The whole point is to make it so that one needn't chase link locations, and instead can focus on typing in the entries themselves, with cross-references resolving themselves neatly.

What do you think?

**Comment by Alamantus** [comment]
Thanks for this post! I've been thinking of adding some way to make it easier for a while, too, because I'm probably the only other person who has linked more words in my Lexiconga dictionary than you, based on your description. Haha. :)

It shouldn't be too hard to add link parsing as you described, but I'll have to figure out how to best handle the numbering. It makes good sense, though! I'll definitely keep this as an enhancement to add when I can!

**Comment by Alamantus** [comment]
July 1st release will help add this feature using `{{otherword}}` and `{{otherword|2}}`
