### ISSUE TITLE
Khmer unicode is not recognized when export

### ISSUE THREAD

**Issue by BunlengC** [Alamantus/Lexiconga#51]
Hello there,

I've created a simple Khmer-English glossary. Khmer characters are Unicode and it displays fine on https://lexicon.ga/. However, when the words are exported, the definition column in Khmer is illegible. 

Any comment or help? Thank you!

![Lexicon ga-1](https://user-images.githubusercontent.com/69565167/89972443-15f0ff80-dc88-11ea-918b-dec5fdda5412.JPG)
![Lexicon ga-2](https://user-images.githubusercontent.com/69565167/89972446-19848680-dc88-11ea-98ff-624f185ebb33.JPG)

**Comment by Alamantus** [comment]
Hi @BunlengC! This looks like an encoding issue in your spreadsheet program. The file exported by Lexiconga is a raw CSV file, so it doesn't have any extra data to tell your program how to read it.

If you're using Microsoft Excel, you need to import the CSV in a specific way that allows you to tell Excel that the file is Unicode and not ASCII. See this article for a walkthrough and explanation of how to do this: https://www.nextofwindows.com/how-to-display-csv-files-with-unicode-utf-8-encoding-in-excel  
For other spreadsheet programs, you will likely need to follow a similar process.

Once you've imported the file as shown in the article, you can save it as an Excel file (`.xlsx`) and it should load correctly any time you open it in the future.

Please let me know if this does not fix your problem!

**Comment by BunlengC** [comment]
Hello,

Thank you for your reply. The article you provided is helpful and I can now
read the Khmer characters in Excel.

I'll play around more with your program and hopefully I get better.

Keep up the good work. It would be handy to have a standalone program which
can be installed on my laptop. ;-)

All the best,

Bunleng

**Comment by Alamantus** [comment]
@BunlengC Wonderful! I'm so glad you were able to get it working!

A desktop app may be something I work on in the future, but for now, you can at least use Lexiconga offline as long as you've visited the web app once! It stores an offline version of itself in your browser so you can load it and use it even if you don't have internet access, then (if you have an account) it will sync to the server once you reconnect.
