### ISSUE TITLE
Public link not working

### ISSUE THREAD

**Issue by CherryHead56** [Alamantus/Lexiconga#53]
When I try to view my dictionary from the public link, I get an HTTP error 500. I have included the exact screen that comes up.
![Screenshot 2020-10-08 110743](https://user-images.githubusercontent.com/72573520/95497011-851c6480-0956-11eb-82ad-f961df5cfeda.png)

**Comment by Alamantus** [comment]
Thanks so much for reporting this! I'll take a look and see what's going wrong.

**Comment by CherryHead56** [comment]
It works now, Thanks!

**Comment by Alamantus** [comment]
Yes! I was able to fix this on change e1222a43f6412aab0e2fa1586e07fba72ecd8251

Thanks again!
