### ISSUE TITLE
quote-surrounded text, specifically in 'definition' field, vanishes upon any further Edit to that entry

### ISSUE THREAD

**Issue by rudluff** [Alamantus/Lexiconga#54]
My scenario:
![Screenshot_2020-10-16_03-05-09](https://user-images.githubusercontent.com/35908990/96223927-bac7db80-0f5c-11eb-89ad-1a88f7f0e8f1.png)
The first entry+save of the definition with quotes will succeed, as above. But going back to edit it...
![Screenshot_2020-10-16_03-05-24](https://user-images.githubusercontent.com/35908990/96223993-d16e3280-0f5c-11eb-90b7-ea0939f7400b.png)
...and, as you see, the quoted bit is no longer living in the definition field. Not merely a visual glitch/truncation; editing any field in that word entry will result in the truncated bit actually being saved:
![Screenshot_2020-10-16_03-09-33](https://user-images.githubusercontent.com/35908990/96224115-0a0e0c00-0f5d-11eb-8efe-455e577e5085.png)
Cancel Edit keeps it safe, and manually re-entering the deleted bit also preserves it when the word is saved.

This does not occur for any other field (viz the Details field getting to keep its typewriter quotes), so I'm guessing it's just a failure to auto-escape user input in that specific field.

Pretty trivial, and obviously those details should go in the "Details" field (I noticed this as I was cleaning up my Definitions to be less... detailed), but still unexpected behavior. :-)

**Comment by Alamantus** [comment]
@rudluff Thank you so much for reporting this issue! I'll check this out as soon as possible and let you know when I figure it out!

**Comment by Alamantus** [comment]
I figured out what the problem is: quotes are interfering with the HTML, which is obviously wrong. I'll work on fixing it now!

**Comment by Alamantus** [comment]
Ok, I have just uploaded the fix  made in acdc5cbdaa51fa50b269d85906e29ee2f6b77b79 and made sure to apply the fix to any fields that were similarly generated to make sure they would not be a problem in the future!

Thanks again for letting me know about the problem!
